apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma

spec:
  enableLogicalBackup: true
  teamId: flipkart
  numberOfInstances: 2
  standby:
    s3_wal_path: "gs://ck-flipkart-pg-storage-bucket/prod/backup/logical-backup/ck-postgres/0157216e-205a-4136-8f2d-62ee184b9e8c/wal/"
  imagePullSecrets:
    - name: ckn-ghcr-secret
  serviceAccountName: postgres-pod
  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-pod
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
imagePullSecrets:
  - name: ckn-ghcr-secret
