apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: ck-postgres
  namespace: codekarma

spec:
  enableLogicalBackup: true
  teamId: flipkart
  numberOfInstances: 2
  env:
    - name: USE_WALG_RESTORE
      value: "true"
    - name: STANDBY_USE_WALG_RESTORE
      value: "true"
    - name: STANDBY_WALE_ENV_DIR
      value: "/run/etc/wal-e.d/env-standby"
    # These force Spilo to use GCS logic instead of S3 logic for standby
    - name: STANDBY_WALE_GS_PREFIX
      value: "gs://ck-flipkart-pg-storage-bucket/spilo/"
    - name: STANDBY_WALG_GS_PREFIX
      value: "gs://ck-flipkart-pg-storage-bucket/spilo/"

  standby:
    # Fixed: Removed double slash and ensured it points to the UID root
    s3_wal_path: "gs://ck-flipkart-pg-storage-bucket/spilo/ck-postgres/a0709f4d-1661-4f0f-aa89-72a20a2cbf5c"
  imagePullSecrets:
    - name: ckn-ghcr-secret
  serviceAccountName: postgres-pod
  postgresql:
    version: "15"

  volume:
    size: 10Gi
    storageClass: ckn-gcp-sc

  users:
    cknexus:
      - superuser
      - createdb

  databases:
    ckservicedb: cknexus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-pod
  namespace: codekarma
  annotations:
    iam.gke.io/gcp-service-account: codekarma-dev-node-sa@ck-flipkart-pg.iam.gserviceaccount.com
imagePullSecrets:
  - name: ckn-ghcr-secret
